{% set name = "json5" %}
{% set version = "0.8.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "124b0f0da1ed2ff3bfe3a3e9b8630abd3c650852465cb52c15ef60b8e82a73b0"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "
  entry_points:
    - pyjson5 = json5.tool:main

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - json5

about:
  home: https://github.com/dpranke/pyjson5
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python implementation of the JSON5 data format
  dev_url: https://github.com/dpranke/pyjson5

extra:
  recipe-maintainers:
    - ian-r-rose
