{% set name = "json5" %}
{% set version = "0.12.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2743e77b3242f8d03c143dd975a6ec7c52e2f2afe76ed934e53503dd4ad4990

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - pyjson5 = json5.tool:main
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools >=61.0
    - wheel
  run:
    - python

# E   FileNotFoundError: [Errno 2] No such file or directory: '$SRC_DIR/tests/../sample.json5'
{% set deselect_tests = " --deselect=tests/lib_test.py::TestLoads::test_sample_file" %}
test:
  source_files:
    - tests
  imports:
    - json5
    - json5.host
    - json5.lib
    - json5.parser
    - json5.tool
    - json5.version
  commands:
    - pip check
    - pyjson5 --help
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dpranke/pyjson5
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python implementation of the JSON5 data format
  description: A Python implementation of the JSON5 data format
  dev_url: https://github.com/dpranke/pyjson5
  doc_url: https://github.com/dpranke/pyjson5/blob/main/README.md

extra:
  recipe-maintainers:
    - ian-r-rose
